name: mlp
action_horizon: ${action_horizon}
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
predict_past_actions: ${predict_past_actions}
flatten_obs: true


hidden_dims: [256, 256, 256]
dropout: 0.1
residual: false

loss_fn: MSELoss  # MSELoss | L1Loss
confusion_loss_beta: 0.0

projection_dim: 128