sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_50_np.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_50_p.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_100_np.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_100_p.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_150_np.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_150_p.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_200_np.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_200_p.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_250_np.sh
sleep 10
sbatch slurm/supercloud/one_leg/ta_sweep/one_ta_250_p.sh
