regularization:
  feature_layernorm: false
  weight_decay: 1e-6

  feature_noise: 0.0
  feature_dropout: 0.0
  proprioception_dropout: 0.0
  front_camera_dropout: 0.0
  wrist_camera_dropout: 0.0
  vib_front_feature_beta: 0.0

  image_augmention:
    random_erase: false

  state_noise: 0.0
  
